name = "INTRO"

description =  """
Intro to the DCPU-16. Pass the input to the output
Use RCV X, 0 to receive input on Ch:0, and SND X, 1 to send output on Ch:1
Remember to make your program loop by using SET PC, 0
"""

short_description = "PASS THE INPUT TO THE OUTPUT"

hardware = []

input_channels = [0]
output_channels = [1]

section = "TUTORIAL"