levels = [
"INTRO",
"SHIFT",
"SPLIT",
"STREAM_MERGER",
"MAX",
"MIN",
"DIFFOUT",
"SPACESHIP_OPERATOR",
"EXPAND",
"POW",
"CHECKSUM",
"REVERSAL",
"BUBBLE",
"HWENUMERATE",
"BAD_ATTITUDE",
"LIFTOFF",
"HELLOWORLD",
"SANDBOX"
]